# **Решение задач по библиотеке Pandas**

# **1. Создание объектов**

Создать объект `Series` с индексами `a, b, c` и значениями `1, 2, 3` соответственно:
- из списка;
- из массива `NumPy`;
- из словаря.

In [ ]:
import pandas as pd
import numpy as np

s1 =  pd.Series([1,2,3], ['a', 'b', 'c'])
print(s1)
s2 = pd.Series(np.array([1,2,3]), np.array(['a', 'b', 'c']))
print(s2)
s3 = pd.Series({'a': 1, 'b' : 2, 'c' : 3})
print(s3)

a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
dtype: int64

Создать таблицу из 2-х строк и 3-х столбцов из 2D массива Numpy:
- 1, 2, 3;
- 4, 5, 6.
Названия столбцов: 'A', 'B', 'C'.

In [ ]:
s1 = pd.DataFrame(np.array([[1, 2, 3],[4, 5, 6]]), columns=['A','B', 'C'])
s1

   A  B  C
0  1  2  3
1  4  5  6

Создать таблицу с именем `df`, содержащую следующие столбцы и соответствующие данные:
- `'age'` - 27, 38, 31, 45, 54, 19, 17, 19, 31, 19;
- `'gender'` - 'м', 'ж', 'м', 'ж', 'ж', 'ж', 'м', 'ж', 'м', 'м';
- `'region'` - 'Курск', 'Москва', 'Орёл', 'Москва',  Тверь', 'Тула', 'Москва', 'Воронеж', 'Липецк', 'Орёл';
- `'sum'` - 908.45, 1200, 1050.77, 1620.54, 1547.60,  850, 1010.10, 1352, 1485.90, 986;
- `'num'`- 15, 9, 11, 2, 1, 7, 2, 4, 4, 3.

Использовать механизм словарей.

In [45]:
df = pd.DataFrame({'age' : [27, 38, 31, 45, 54, 19, 17, 19, 31, 19],
                'gender' : [ 'м', 'ж', 'м', 'ж', 'ж', 'ж', 'м', 'ж', 'м', 'м'],
                'region' : [ 'Курск', 'Москва', 'Орёл', 'Москва', 'Тверь', 'Тула', 'Москва', 'Воронеж', 'Липецк', 'Орёл'],
                'sum' : [ 908.45, 1200, 1050.77, 1620.54, 1547.60, 850, 1010.10, 1352, 1485.90, 986],
                'num' : [15, 9, 11, 2, 1, 7, 2, 4, 4, 3]
                })
df

   age gender   region      sum  num
0   27      м    Курск   908.45   15
1   38      ж   Москва  1200.00    9
2   31      м     Орёл  1050.77   11
3   45      ж   Москва  1620.54    2
4   54      ж    Тверь  1547.60    1
5   19      ж     Тула   850.00    7
6   17      м   Москва  1010.10    2
7   19      ж  Воронеж  1352.00    4
8   31      м   Липецк  1485.90    4
9   19      м     Орёл   986.00    3

Прочитать html страницу по адресу https://www.statdata.ru/russia и создать `DataFrame`, который содержит первую таблицу с этой страницы.

In [ ]:
df_html = pd.read_html('https://www.statdata.ru/russia')
df_html

[       0            1           2       3    4
 0    Год    Население     Прирост       %  NaN
 1   2024  146 203 613   — 243 811  — 0,17    ↘
 2   2023  146 447 424     889 848     061    ↗
 3   2022  145 557 576   — 613 439  — 0,42    ↘
 4   2021  146 171 015   — 577 575  — 0,39    ↘
 5   2020  146 748 590     481 302     033    ↗
 6   2015  146 267 288   3 410 752     239    ↗
 7   2010  142 856 536  -4 033 592  — 2,75    ↘
 8   2000  146 890 128   — 774 953  — 0,52    ↘
 9   1990  147 665 081   9 538 481     691    ↗
 10  1980  138 126 600   8 047 390     619    ↗
 11  1970  130 079 210  11 033 410     927    ↗
 12  1960  119 045 800  16 978 800    1663    ↗
 13  1950  102 067 000  -6 310 000  — 5,82    ↗
 14  1939  108 377 000   7 485 756     742    ↗
 15  1926  100 891 244  33 418 244    4953    ↗
 16  1897   67 473 000           —       —  NaN,
                        0             1             2       3  \
 0             Показатель  Человек 2021  Человек 2020   (+/-)
 1             Родившихся       1 402,8       1 435,8  — 33,0
 2                Умерших       2 445,5       2 124,5    3210
 3  Естест. прирост/убыль     — 1 042,7       — 688,7     NaN
 4                 Браков          9236          7708    1528
 5               Разводов           644           564     802

                    4                  5
 0  На 1000 чел. 2021  На 1000 чел. 2020
 1                 96                 98
 2                168                145
 3              — 7,2              — 4,7
 4                 63                 53
 5                  4                  4  ,
                                           0             1                2  \
 0                                Показатель  2021 человек  2021 на 10 тыс.
 1                          Миграция — всего           NaN              NaN
 2                                 прибывшие     4 263 275              292
 3                                  выбывшие     3 833 368              263
 4                 миграц. прирост / снижен.       429 907               30
 5            в том числе: в пределах России           NaN              NaN
 6                                 прибывшие     3 595 353             2465
 7                                  выбывшие     3 595 353             2465
 8                 миграц. прирост / снижен.             —                —
 9                    международная миграция           NaN              NaN
 10                                прибывшие       667 922              458
 11                                 выбывшие       238 015              163
 12                миграц. прирост / снижен.       429 907               30
 13  в т.ч.: с государствами-участниками СНГ           NaN              NaN
 14                                прибывшие       606 178              416
 15                                 выбывшие       210 339              144
 16                миграц. прирост / снижен.       395 839               27
 17           со странами дальнего зарубежья           NaN              NaN
 18                                прибывшие        61 744               42
 19                                 выбывшие        27 676               19
 20                миграц. прирост / снижен.         34068               23

                3                4
 0   2020 человек  2020 на 10 тыс.
 1            NaN              NaN
 2      4 120 743              281
 3      4 014 269              274
 4        106 474                7
 5            NaN              NaN
 6      3 526 597             2408
 7      3 526 597             2408
 8              —                —
 9            NaN              NaN
 10       594 146              406
 11       487 672              333
 12       106 474                7
 13           NaN              NaN
 14       535 923              366
 15       417 059              285
 16       118 864                8
 17           NaN              NaN
 18        58 223               40
 19        70 613               48
 20        -12390              -08  ,
                    0           1
 0          г. Москва  13 104 177
 1    Московская обл.   8 591 736
 2  Краснодарский кр.   5 819 345
 3  г.Санкт-Петербург   5 600 044,
    0                   1              2
 0  №               Город  На 01.01.2023
 1  1           г. Москва     13 104 177
 2  2  г. Санкт-Петербург      5 600 044
 3  3      г. Новосибирск      1 635 338,
                 0           1
 0  Центральный ФО  40 240 256
 1  Приволжский ФО  28 683 247
 2    Сибирский ФО  16 645 802,
    0                  1            2           3  \
 0  №  Этническая группа      Человек  % от всего
 1  —          ВСЕГО, РФ  147 182 123    100,00 %
 2  1            Русские  105 579 179     71,73 %
 3  2             Татары    4 713 669      3,20 %
 4  3            Чеченцы    1 674 854      1,14 %

                                4
 0  % от указавших национальность
 1                              —
 2                        80,85 %
 3                         3,61 %
 4                         1,28 %  ,
                                        0  \
 0                      Москва. Увеличить
 1  Новосибирск. Академгородок. Увеличить

                                          1
 0  Санкт-Петербург. Лахта центр. Увеличить
 1                  Екатеринбург. Увеличить  ,
       0          1          2          3          4          5          6
 0  Годы  1801–1810  1811–1820  1821–1830  1831–1840  1841–1850  1851–1860
 1   ОКР       43.7       40.0       42.7       45.6       49.7       52.4
 2  Годы  1861–1870  1871–1880  1881–1890  1891–1900  1901–1910  1911–1914
 3   ОКР       50.3       50.4       50.4       49.2       46.8       43.9,
       0                      1           2          3                     4   \
 0   Годы  Численность населения  Родившихся    Умерших  Естественный прирост
 1   1927             93 604 000   4 688 000  2 705 000              1983 000
 2   1928             95 587 000   4 723 000  2 589 000              2134 000
 3   1929             97 721 000   4 633 000  2 819 000              1814 000
 4   1930             99 566 000   4 413 000  2 738 000              1675 000
 5   1931            101 272 000   4 412 000  3 090 000              1322 000
 6   1932            102 624 000   4 058 000  3 077 000               981 000
 7   1933            103 648 000   3 313 000  5 239 000            −1 926 000
 8   1934            101 763 000   2 923 000  2 659 000               264 000
 9   1935            102 080 000   3 577 000  2 421 000              1156 000
 10  1936            103 288 000   3 899 000  2 719 000              1180 000
 11  1937            104 520 000   4 377 000  2 760 000              1617 000
 12  1938            106 195 000   4 379 000  2 739 000              1640 000
 13  1939            107 892 000   4 329 000  2 600 000              1729 000
 14  1940            109 678 000   3 814 000  2 561 000              1253 000
 15  1941            110 988 000   3 650 000  2 283 000              1367 000

                      5                 6                 7          8   \
 0   Общ. прирост насел.  ОКР на 1000 жит.  ОКС на 1000 жит.  КЕП общий
 1                   NaN             49.04             28.30      20.74
 2                   NaN             48.33             26.49      21.84
 3                   NaN             46.53             28.31      18.22
 4                   NaN             43.58             27.04      16.54
 5                   NaN             42.99             30.11      12.88
 6                   NaN             39.15             29.69       9.46
 7                   NaN             32.56             51.48     −18.93
 8                   NaN             28.63             26.05       2.59
 9                   NaN             34.63             23.44      11.19
 10                  NaN             37.30             26.01      11.29
 11                  NaN             41.22             25.99      15.23
 12                  NaN             40.59             25.39      15.20
 13                  NaN             39.47             23.71      15.76
 14                  NaN             34.36             23.07      11.29
 15                  NaN             32.50             20.33      12.17

            9          10        11           12           13         14
 0   СКР общий  СКР город  СКР село  ОПЖ мужчины  ОПЖ женщины  ОПЖ общая
 1       6.653        NaN       NaN         33.7         37.9        NaN
 2       6.534        NaN       NaN         35.9         40.4        NaN
 3       6.201        NaN       NaN         33.7         38.2        NaN
 4       5.785        NaN       NaN         34.6         38.7        NaN
 5       5.611        NaN       NaN         30.7         35.5        NaN
 6       5.042        NaN       NaN         30.5         35.7        NaN
 7       4.069        NaN       NaN         15.2         19.5        NaN
 8       3.586        NaN       NaN         30.5         35.7        NaN
 9       4.259        NaN       NaN         33.1         38.4        NaN
 10      4.554        NaN       NaN         30.4         35.7        NaN
 11      5.047        NaN       NaN         30.5         40.0        NaN
 12      4.987        NaN       NaN         31.7         42.5        NaN
 13      4.881        NaN       NaN         34.9         42.6        NaN
 14      4.252        NaN       NaN         35.7         41.9        NaN
 15        NaN        NaN       NaN          NaN          NaN        NaN  ,
       0                      1           2          3                     4   \
 0   Годы  Численность населения  Родившихся    Умерших  Естественный прирост
 1   1946             97 548 000   2 546 000  1 210 000              1336 000
 2   1947             98 028 000   2 715 000  1 680 000              1035 000
 3   1948             98 834 000   2 516 000  1 310 000              1206 000
 4   1949             99 706 000   3 089 000  1 187 000              1902 000
 5   1950            101 160 000   2 859 000  1 180 000              1679 000
 6   1951            102 833 000   2 938 000  1 210 000              1728 000
 7   1952            104 439 000   2 928 000  1 138 000              1790 000
 8   1953            106 164 000   2 822 000  1 118 000              1704 000
 9   1954            107 828 000   3 048 000  1 133 000              1915 000
 10  1955            109 643 000   2 942 000  1 037 000              1905 000
 11  1956            111 572 000   2 827 000    956 000              1871 000
 12  1957            113 327 000   2 880 000  1 017 000              1863 000
 13  1958            115 035 000   2 861 000    931 000              1930 000
 14  1959            116 749 000   2 796 228    920 225              1876 003
 15  1960            118 307 000   2 782 353    886 090              1896 263
 16  1961            119 906 000   2 662 135    901 637              1760 498
 17  1962            121 586 000   2 482 539    949 648              1532 891
 18  1963            123 128 000   2 331 505    932 055              1399 450
 19  1964            124 514 000   2 121 994    901 751              1220 243
 20  1965            125 744 000   1 990 520    958 789              1031 731
 21  1966            126 749 000   1 957 763    974 299               983 464
 22  1967            127 608 000   1 851 041  1 017 034               834 007
 23  1968            128 361 000   1 816 509  1 040 096               776 413
 24  1969            129 037 000   1 847 592  1 106 640               740 952
 25  1970            129 660 000   1 903 713  1 131 183               772 530
 26  1971            130 252 000   1 974 637  1 143 359               831 278
 27  1972            130 934 000   2 014 638  1 181 802               832 836
 28  1973            131 687 000   1 994 621  1 214 204               780 417
 29  1974            132 434 000   2 079 812  1 222 495               857 317
 30  1975            133 217 000   2 106 147  1 309 710               796 437
 31  1976            134 092 000   2 146 711  1 352 950               793 761
 32  1977            135 026 000   2 156 724  1 387 986               768 738
 33  1978            135 979 000   2 179 030  1 417 377               761 653
 34  1979            136 922 000   2 178 542  1 490 057               688 485
 35  1980            137 758 000   2 202 779  1 525 755               677 024
 36  1981            138 483 000   2 236 608  1 524 286               712 322
 37  1982            139 221 000   2 328 044  1 504 200               823 844
 38  1983            140 067 000   2 478 322  1 563 995               914 327
 39  1984            141 056 000   2 409 614  1 650 866               758 748
 40  1985            142 061 000   2 375 147  1 625 266               749 881
 41  1986            143 033 000   2 485 915  1 497 975               987 940
 42  1987            144 156 000   2 499 974  1 531 585               968 389
 43  1988            145 386 000   2 348 494  1 569 112               779 382
 44  1989            146 505 000   2 160 559  1 583 743               576 816
 45  1990            147 665 081   1 988 858  1 655 993               332 865
 46  1991            148 273 746   1 794 626  1 690 657               103 969

                      5                 6                 7          8   \
 0   Общ. прирост насел.  ОКР на 1000 жит.  ОКС на 1000 жит.  КЕП общий
 1                   NaN              26.0              12.3       13.6
 2                   NaN              27.5              17.0       10.5
 3                   NaN              25.2              13.1       12.1
 4                   NaN              30.5              11.7       18.8
 5                   NaN              27.8              11.5       16.7
 6                   NaN              28.1              11.6       17.0
 7                   NaN              27.6              10.7       17.0
 8                   NaN              26.2              10.4       15.7
 9                   NaN              27.8              10.3       17.6
 10                  NaN              26.4               9.3       17.2
 11                  NaN              24.9               8.4       16.8
 12                  NaN              25.0               8.8       16.7
 13                  NaN              24.5               8.0       17.0
 14                  NaN              23.6               7.8       15.9
 15                  NaN              23.2               7.4       15.8
 16                  NaN              21.9               7.4       14.5
 17                  NaN              20.2               7.7       12.4
 18                  NaN              18.7               7.5       11.2
 19                  NaN              16.9               7.2        9.7
 20                  NaN              15.7               7.6        8.1
 21                  NaN              15.3               7.6        7.7
 22                  NaN              14.4               7.9        6.5
 23                  NaN              14.1               8.1        6.0
 24                  NaN              14.2               8.5        5.7
 25                  NaN              14.6               8.7        5.9
 26                  NaN              15.1               8.7        6.3
 27                  NaN              15.3               9.0        6.3
 28                  NaN              15.1               9.2        5.9
 29                  NaN              15.6               9.2        6.4
 30                  NaN              15.7               9.8        5.9
 31                  NaN              15.9              10.0        5.9
 32                  NaN              15.9              10.2        5.7
 33                  NaN              15.9              10.4        5.6
 34              836 000              15.8              10.8        5.0
 35              725 000              15.9              11.0        4.9
 36              738 000              16.1              10.9        5.1
 37              846 000              16.6              10.7        5.9
 38              989 000              17.6              11.1        6.5
 39             1005 000              17.0              11.6        5.3
 40              972 000              16.6              11.4        5.2
 41             1123 000              17.2              10.4        6.9
 42             1230 000              17.2              10.5        6.7
 43             1119 000              16.0              10.7        5.3
 44             1160 081              14.7              10.7        3.9
 45              608 665              13.4              11.2        2.2
 46              240 946              12.1              11.4        0.7

            9          10        11           12           13         14
 0   СКР общий  СКР город  СКР село  ОПЖ мужчины  ОПЖ женщины  ОПЖ общая
 1       2.806        NaN       NaN         46.6         55.3        NaN
 2       2.937        NaN       NaN         39.9         49.8        NaN
 3       2.609        NaN       NaN         47.0         56.0        NaN
 4       3.196        NaN       NaN         51.0         59.8        NaN
 5       2.889        NaN       NaN         52.3         61.0        NaN
 6       2.921        NaN       NaN         52.3         60.6        NaN
 7       2.867        NaN       NaN         54.6         62.9        NaN
 8       2.737        NaN       NaN         55.5         63.9        NaN
 9       2.964        NaN       NaN         55.9         64.1        NaN
 10      2.834        NaN       NaN         58.3         66.6        NaN
 11      2.712        NaN       NaN         60.1         68.8        NaN
 12      2.741        NaN       NaN         59.7         68.4        NaN
 13      2.690        NaN       NaN         61.8         70.4        NaN
 14       2.58       2.03      3.34        62.84        71.14      67.65
 15       2.56       2.06      3.26        63.67        72.31      68.67
 16       2.47       2.04      3.08        63.91        72.63      68.92
 17       2.36       1.98      2.92        63.67        72.27      68.58
 18       2.31       1.93      2.87        64.12        72.78      69.05
 19       2.19       1.88      2.66        64.89        73.58      69.85
 20       2.14       1.82      2.58        64.37        73.33      69.44
 21       2.13       1.85      2.58        64.29        73.55      69.51
 22       2.03       1.79      2.46        64.02        73.43      69.30
 23       1.98       1.75      2.44        63.73        73.56      69.26
 24       1.99       1.78      2.44        63.07        73.29      68.74
 25       2.00       1.77      2.52        63.07        73.44      68.86
 26       2.02       1.80      2.60        63.24        73.77      69.12
 27       2.03       1.81      2.59        63.24        73.62      69.02
 28       1.96       1.75      2.55        63.28        73.56      69.00
 29       2.00       1.78      2.63        63.12        73.77      68.99
 30       1.97       1.76      2.64        62.48        73.23      68.35
 31       1.96       1.74      2.62        62.19        73.04      68.10
 32       1.92       1.72      2.58        61.82        73.19      67.97
 33       1.90       1.70      2.55        61.83        73.23      68.01
 34       1.87       1.67      2.54        61.49        73.02      67.73
 35       1.87       1.68      2.51        61.38        72.96      67.70
 36       1.88       1.69      2.55        61.61        73.18      67.92
 37       1.96       1.76      2.63        62.24        73.64      68.38
 38       2.11       1.89      2.76        62.15        73.41      68.15
 39       2.06       1.86      2.69        61.71        72.96      67.67
 40       2.05       1.87      2.68        62.72        73.23      68.33
 41       2.18       1.98      2.83        64.77        74.22      69.95
 42       2.23       2.04      2.88        64.83        74.26      69.96
 43       2.12       1.96      2.80        64.61        74.25      69.81

Прочитать файл "Страховка", перевести его в `DataFrame` и вывести первые 5 строк.

In [5]:
import pandas as pd
df_csv = pd.read_csv('/content/Страховка.csv')
df_csv.head(5)

   Возраст Пол  Индекс массы  Дети Курение        Регион    Стоимость
0       19   Ж        27.900     0      да     юго-запад  16884.92400
1       18   М        33.770     1     нет    юго-восток   1725.55230
2       28   М        33.000     3     нет    юго-восток   4449.46200
3       33   М        22.705     0     нет  северо-запад  21984.47061
4       32   М        28.880     0     нет  северо-запад   3866.85520

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Для таблицы `df`:
1. Вывести первые 5 записей таблицы.
2. Вывести формат данных каждого столбца.
3. Вывести количество строк и столбцов.
4. Создать список с именами столбцов.

In [ ]:
df_csv.head(5)

   Возраст Пол  Индекс массы  Дети Курение        Регион    Стоимость
0       19   Ж        27.900     0      да     юго-запад  16884.92400
1       18   М        33.770     1     нет    юго-восток   1725.55230
2       28   М        33.000     3     нет    юго-восток   4449.46200
3       33   М        22.705     0     нет  северо-запад  21984.47061
4       32   М        28.880     0     нет  северо-запад   3866.85520

In [8]:
df_csv.dtypes

Возраст           int64
Пол              object
Индекс массы    float64
Дети              int64
Курение          object
Регион           object
Стоимость       float64
dtype: object

In [ ]:
df_csv.shape

(1338, 7)

In [10]:
list(df_csv.columns)

['Возраст', 'Пол', 'Индекс массы', 'Дети', 'Курение', 'Регион', 'Стоимость']

# **2. Индексация и выборка данных**

Вывести фрагмент таблицы `df`, содержащий только столбцы `'age'` и `'gender'`.

In [14]:
df[['age', 'gender']]

   age gender
0   27      м
1   38      ж
2   31      м
3   45      ж
4   54      ж
5   19      ж
6   17      м
7   19      ж
8   31      м
9   19      м

Вывести фрагмент таблицы `df`, содержащий с 3-й по 5-ю строки включительно:
- использовать индикатор `loc`;
- использовать индикатор `iloc`.

In [15]:
print(df.loc[3:5])

print(df.iloc[3:6])

   age gender  region      sum  num
3   45      ж  Москва  1620.54    2
4   54      ж   Тверь  1547.60    1
5   19      ж    Тула   850.00    7
   age gender  region      sum  num
3   45      ж  Москва  1620.54    2
4   54      ж   Тверь  1547.60    1
5   19      ж    Тула   850.00    7

Вывести фрагмент таблицы `df`, содержащий первые 3 строки и столбцы `'age'` и `'sum'`:
- использовать индикатор `loc`;
- использовать индикатор `iloc`.

In [ ]:
df[['age', 'sum']].loc[:2], df[['age', 'sum']].iloc[:3]

(   age      sum
 0   27   908.45
 1   38  1200.00
 2   31  1050.77,
    age      sum
 0   27   908.45
 1   38  1200.00
 2   31  1050.77)

Выбрать элемент, находящийся в первой строке в столбце `'sum'`:
- использовать индикатор `loc`;
- использовать индикатор `iloc`.

In [17]:
df['sum'].loc[1], df['sum'].iloc[1]

(1200.0, 1200.0)

# **3. Выбор данных по условию**

Выбрать людей в возрасте 31 год.

In [21]:
print(df[ df['age'] == 31])
print(df.loc[(df['age']== 31)])

   age gender  region      sum  num
2   31      м    Орёл  1050.77   11
8   31      м  Липецк  1485.90    4
   age gender  region      sum  num
2   31      м    Орёл  1050.77   11
8   31      м  Липецк  1485.90    4

Для людей в возрасте 31 год вывести регион и сумму покупок.

In [26]:
df[df['age'] == 31][['region', 'sum']]
print(df.loc[(df['age'] == 31), ['region', 'sum']])

   region      sum
2    Орёл  1050.77
8  Липецк  1485.90

Выбрать людей в возрасте от 30 до 40 лет.

In [37]:
print(df[df['age'].between(30, 40)])
print(df[ (df['age'] >= 30) & (df['age'] < 40) ])
print(df.loc[((df['age'] >= 30) & (df['age'] < 40))])

   age gender  region      sum  num
1   38      ж  Москва  1200.00    9
2   31      м    Орёл  1050.77   11
8   31      м  Липецк  1485.90    4
   age gender  region      sum  num
1   38      ж  Москва  1200.00    9
2   31      м    Орёл  1050.77   11
8   31      м  Липецк  1485.90    4
   age gender  region      sum  num
1   38      ж  Москва  1200.00    9
2   31      м    Орёл  1050.77   11
8   31      м  Липецк  1485.90    4

Выбрать людей в возрасте меньше 30 лет, проживающих в Курске или Орле.

In [39]:
print(df[ (df['age'] < 30) & ( (df['region'] == 'Орёл') | (df['region'] == 'Курск') )])
print(df.loc[(df['age'] < 30) & (df['region'].isin(['Орёл', 'Курск']))])

   age gender region     sum  num
0   27      м  Курск  908.45   15
9   19      м   Орёл  986.00    3
   age gender region     sum  num
0   27      м  Курск  908.45   15
9   19      м   Орёл  986.00    3

Выбрать людей, которые не проживают в Москве.

In [40]:
print(df[ (df['region'] != 'Москва') ])
print(df.loc[(df['region'] != 'Москва')])
print(df[ ~(df['region'] == 'Москва')])

   age gender   region      sum  num
0   27      м    Курск   908.45   15
2   31      м     Орёл  1050.77   11
4   54      ж    Тверь  1547.60    1
5   19      ж     Тула   850.00    7
7   19      ж  Воронеж  1352.00    4
8   31      м   Липецк  1485.90    4
9   19      м     Орёл   986.00    3
   age gender   region      sum  num
0   27      м    Курск   908.45   15
2   31      м     Орёл  1050.77   11
4   54      ж    Тверь  1547.60    1
5   19      ж     Тула   850.00    7
7   19      ж  Воронеж  1352.00    4
8   31      м   Липецк  1485.90    4
9   19      м     Орёл   986.00    3
   age gender   region      sum  num
0   27      м    Курск   908.45   15
2   31      м     Орёл  1050.77   11
4   54      ж    Тверь  1547.60    1
5   19      ж     Тула   850.00    7
7   19      ж  Воронеж  1352.00    4
8   31      м   Липецк  1485.90    4
9   19      м     Орёл   986.00    3

Выбрать столбцы с типами данных `int` и `float`.

In [ ]:
df.select_dtypes([int, float])

   age      sum  num
0   27   908.45   15
1   38  1200.00    9
2   31  1050.77   11
3   45  1620.54    2
4   54  1547.60    1
5   19   850.00    7
6   17  1010.10    2
7   19  1352.00    4
8   31  1485.90    4
9   19   986.00    3

# **4. Операции со строками и столбцами**

В таблицу `df` добавить новый столбец `'payment'` (способ оплаты), принимающий следующие значения Sber Pay, cash, QIWI Кошелёк, bank card, QR-код, cash, Sber Pay, bank card, bank card, Sber Pay.

In [46]:
df =df.assign(payment=['Sber Pay', 'cash', 'QIWI Кошелёк', 'bank card', 'QR-код', 'cash', 'Sber Pay', 'bank card', 'bank card', 'Sber Pay'])

Переименовать столбец `'num'` в `'purchase'`.

In [47]:
df = df.rename(columns={'num': 'purchase'})
df

   age gender   region      sum  purchase       payment
0   27      м    Курск   908.45        15      Sber Pay
1   38      ж   Москва  1200.00         9          cash
2   31      м     Орёл  1050.77        11  QIWI Кошелёк
3   45      ж   Москва  1620.54         2     bank card
4   54      ж    Тверь  1547.60         1        QR-код
5   19      ж     Тула   850.00         7          cash
6   17      м   Москва  1010.10         2      Sber Pay
7   19      ж  Воронеж  1352.00         4     bank card
8   31      м   Липецк  1485.90         4     bank card
9   19      м     Орёл   986.00         3      Sber Pay

Создать и добавить в таблицу `df` новый стобец `'average'`, содержащий среднюю стоимость покупок.

1. Решить задачу с использованием метода `apply()` и lambda-функции.

In [ ]:
df['average'] = df.apply(lambda row: row['sum'] / row['purchase'], axis =1 )
df

   age gender   region      sum  purchase       payment      average
0   27      м    Курск   908.45        15      Sber Pay    60.563333
1   38      ж   Москва  1200.00         9          cash   133.333333
2   31      м     Орёл  1050.77        11  QIWI Кошелёк    95.524545
3   45      ж   Москва  1620.54         2     bank card   810.270000
4   54      ж    Тверь  1547.60         1        QR-код  1547.600000
5   19      ж     Тула   850.00         7          cash   121.428571
6   17      м   Москва  1010.10         2      Sber Pay   505.050000
7   19      ж  Воронеж  1352.00         4     bank card   338.000000
8   31      м   Липецк  1485.90         4     bank card   371.475000
9   19      м     Орёл   986.00         3      Sber Pay   328.666667

Удалить столбец `'average'`.

In [ ]:
df = df.drop('average', axis=1)
df

   age gender   region      sum  purchase       payment
0   27      м    Курск   908.45        15      Sber Pay
1   38      ж   Москва  1200.00         9          cash
2   31      м     Орёл  1050.77        11  QIWI Кошелёк
3   45      ж   Москва  1620.54         2     bank card
4   54      ж    Тверь  1547.60         1        QR-код
5   19      ж     Тула   850.00         7          cash
6   17      м   Москва  1010.10         2      Sber Pay
7   19      ж  Воронеж  1352.00         4     bank card
8   31      м   Липецк  1485.90         4     bank card
9   19      м     Орёл   986.00         3      Sber Pay

Решить задачу с использованием функции `.map()`.

Создать и добавить в таблицу `df` новый стобец `'rating'`, содержащий рейтинг покупателей в зависимости от средней стоимости покупок:
- 1 - средняя стоимость покупок меньше < 500;
- 2 - средняя стоимость покупок >= 500 и < 1000;
- 3 - средняя стоимость покупок >= 1000.

In [53]:
df['average_cost'] = df['sum'] / df['purchase']
def set_rating(average_cost):
  if average_cost < 500:
    return "1"
  elif average_cost < 1000:
    return "2"
  else:
    return "3"

df['rating'] = df['average_cost'].map(set_rating)
print(df)

   age gender   region      sum  purchase       payment  average_cost rating
0   27      м    Курск   908.45        15      Sber Pay     60.563333      1
1   38      ж   Москва  1200.00         9          cash    133.333333      1
2   31      м     Орёл  1050.77        11  QIWI Кошелёк     95.524545      1
3   45      ж   Москва  1620.54         2     bank card    810.270000      2
4   54      ж    Тверь  1547.60         1        QR-код   1547.600000      3
5   19      ж     Тула   850.00         7          cash    121.428571      1
6   17      м   Москва  1010.10         2      Sber Pay    505.050000      2
7   19      ж  Воронеж  1352.00         4     bank card    338.000000      1
8   31      м   Липецк  1485.90         4     bank card    371.475000      1
9   19      м     Орёл   986.00         3      Sber Pay    328.666667      1